"""S&P 500 constituent snapshot used by Stock Game Pro.
Snapshot refreshed 2026-08-22 from the public constituent table; 503 listed securities represent 500 companies because several issuers have multiple share classes.
"""

SP500_CONSTITUENTS = [
    ('MMM', '3M', 'Industrials', 0.0018, 'MMM', 'Industrial Conglomerates'),
    ('AOS', 'A. O. Smith', 'Industrials', 0.0018, 'AOS', 'Building Products'),
    ('ABT', 'Abbott Laboratories', 'Health Care', 0.0017, 'ABT', 'Health Care Equipment'),
    ('ABBV', 'AbbVie', 'Health Care', 0.0017, 'ABBV', 'Biotechnology'),
    ('ACN', 'Accenture', 'Information Technology', 0.0023, 'ACN', 'IT Consulting & Other Services'),
    ('ADBE', 'Adobe Inc.', 'Information Technology', 0.0023, 'ADBE', 'Application Software'),
    ('AMD', 'Advanced Micro Devices', 'Information Technology', 0.0023, 'AMD', 'Semiconductors'),
    ('AES', 'AES Corporation', 'Utilities', 0.0012, 'AES', 'Independent Power Producers & Energy Traders'),
    ('AFL', 'Aflac', 'Financials', 0.0017, 'AFL', 'Life & Health Insurance'),
    ('A', 'Agilent Technologies', 'Health Care', 0.0017, 'A', 'Life Sciences Tools & Services'),
    ('APD', 'Air Products', 'Materials', 0.002, 'APD', 'Industrial Gases'),
    ('ABNB', 'Airbnb', 'Consumer Discretionary', 0.0021, 'ABNB', 'Hotels, Resorts & Cruise Lines'),
    ('AKAM', 'Akamai Technologies', 'Information Technology', 0.0023, 'AKAM', 'Internet Services & Infrastructure'),
    ('ALB', 'Albemarle Corporation', 'Materials', 0.002, 'ALB', 'Specialty Chemicals'),
    ('ARE', 'Alexandria Real Estate Equities', 'Real Estate', 0.0016, 'ARE', 'Office REITs'),
    ('ALGN', 'Align Technology', 'Health Care', 0.0017, 'ALGN', 'Health Care Supplies'),
    ('ALLE', 'Allegion', 'Industrials', 0.0018, 'ALLE', 'Building Products'),
    ('LNT', 'Alliant Energy', 'Utilities', 0.0012, 'LNT', 'Electric Utilities'),
    ('ALL', 'Allstate', 'Financials', 0.0017, 'ALL', 'Property & Casualty Insurance'),
    ('GOOGL', 'Alphabet Inc. (Class A)', 'Communication Services', 0.0022, 'GOOGL', 'Interactive Media & Services'),
    ('GOOG', 'Alphabet Inc. (Class C)', 'Communication Services', 0.0022, 'GOOG', 'Interactive Media & Services'),
    ('MO', 'Altria', 'Consumer Staples', 0.0012, 'MO', 'Tobacco'),
    ('AMZN', 'Amazon', 'Consumer Discretionary', 0.0021, 'AMZN', 'Broadline Retail'),
    ('AMCR', 'Amcor', 'Materials', 0.002, 'AMCR', 'Paper & Plastic Packaging Products & Materials'),
    ('AEE', 'Ameren', 'Utilities', 0.0012, 'AEE', 'Multi-Utilities'),
    ('AEP', 'American Electric Power', 'Utilities', 0.0012, 'AEP', 'Electric Utilities'),
    ('AXP', 'American Express', 'Financials', 0.0017, 'AXP', 'Consumer Finance'),
    ('AIG', 'American International Group', 'Financials', 0.0017, 'AIG', 'Multi-line Insurance'),
    ('AMT', 'American Tower', 'Real Estate', 0.0016, 'AMT', 'Telecom Tower REITs'),
    ('AWK', 'American Water Works', 'Utilities', 0.0012, 'AWK', 'Water Utilities'),
    ('AMP', 'Ameriprise Financial', 'Financials', 0.0017, 'AMP', 'Asset Management & Custody Banks'),
    ('AME', 'Ametek', 'Industrials', 0.0018, 'AME', 'Electrical Components & Equipment'),
    ('AMGN', 'Amgen', 'Health Care', 0.0017, 'AMGN', 'Biotechnology'),
    ('APH', 'Amphenol', 'Information Technology', 0.0023, 'APH', 'Electronic Components'),
    ('ADI', 'Analog Devices', 'Information Technology', 0.0023, 'ADI', 'Semiconductors'),
    ('AON', 'Aon plc', 'Financials', 0.0017, 'AON', 'Insurance Brokers'),
    ('APA', 'APA Corporation', 'Energy', 0.0021, 'APA', 'Oil & Gas Exploration & Production'),
    ('APO', 'Apollo Global Management', 'Financials', 0.0017, 'APO', 'Asset Management & Custody Banks'),
    ('AAPL', 'Apple Inc.', 'Information Technology', 0.0023, 'AAPL', 'Technology Hardware, Storage & Peripherals'),
    ('AMAT', 'Applied Materials', 'Information Technology', 0.0023, 'AMAT', 'Semiconductor Materials & Equipment'),
    ('APP', 'AppLovin', 'Communication Services', 0.0022, 'APP', 'Advertising'),
    ('APTV', 'Aptiv', 'Consumer Discretionary', 0.0021, 'APTV', 'Automotive Parts & Equipment'),
    ('ACGL', 'Arch Capital Group', 'Financials', 0.0017, 'ACGL', 'Property & Casualty Insurance'),
    ('ADM', 'Archer Daniels Midland', 'Consumer Staples', 0.0012, 'ADM', 'Agricultural Products & Services'),
    ('ARES', 'Ares Management', 'Financials', 0.0017, 'ARES', 'Asset Management & Custody Banks'),
    ('ANET', 'Arista Networks', 'Information Technology', 0.0023, 'ANET', 'Communications Equipment'),
    ('AJG', 'Arthur J. Gallagher & Co.', 'Financials', 0.0017, 'AJG', 'Insurance Brokers'),
    ('AIZ', 'Assurant', 'Financials', 0.0017, 'AIZ', 'Multi-line Insurance'),
    ('T', 'AT&T', 'Communication Services', 0.0022, 'T', 'Integrated Telecommunication Services'),
    ('ATO', 'Atmos Energy', 'Utilities', 0.0012, 'ATO', 'Gas Utilities'),
    ('ADSK', 'Autodesk', 'Information Technology', 0.0023, 'ADSK', 'Application Software'),
    ('ADP', 'Automatic Data Processing', 'Industrials', 0.0018, 'ADP', 'Human Resource & Employment Services'),
    ('AZO', 'AutoZone', 'Consumer Discretionary', 0.0021, 'AZO', 'Automotive Retail'),
    ('AVY', 'Avery Dennison', 'Materials', 0.002, 'AVY', 'Paper & Plastic Packaging Products & Materials'),
    ('AXON', 'Axon Enterprise', 'Industrials', 0.0018, 'AXON', 'Aerospace & Defense'),
    ('BKR', 'Baker Hughes', 'Energy', 0.0021, 'BKR', 'Oil & Gas Equipment & Services'),
    ('BALL', 'Ball Corporation', 'Materials', 0.002, 'BALL', 'Metal, Glass & Plastic Containers'),
    ('BAC', 'Bank of America', 'Financials', 0.0017, 'BAC', 'Diversified Banks'),
    ('BAX', 'Baxter International', 'Health Care', 0.0017, 'BAX', 'Health Care Equipment'),
    ('BDX', 'Becton Dickinson', 'Health Care', 0.0017, 'BDX', 'Health Care Equipment'),
    ('BRK-B', 'Berkshire Hathaway', 'Financials', 0.0017, 'BRK.B', 'Multi-Sector Holdings'),
    ('BBY', 'Best Buy', 'Consumer Discretionary', 0.0021, 'BBY', 'Computer & Electronics Retail'),
    ('TECH', 'Bio-Techne', 'Health Care', 0.0017, 'TECH', 'Life Sciences Tools & Services'),
    ('BIIB', 'Biogen', 'Health Care', 0.0017, 'BIIB', 'Biotechnology'),
    ('BLK', 'BlackRock', 'Financials', 0.0017, 'BLK', 'Asset Management & Custody Banks'),
    ('BX', 'Blackstone Inc.', 'Financials', 0.0017, 'BX', 'Asset Management & Custody Banks'),
    ('XYZ', 'Block, Inc.', 'Financials', 0.0017, 'XYZ', 'Transaction & Payment Processing Services'),
    ('BNY', 'BNY Mellon', 'Financials', 0.0017, 'BNY', 'Asset Management & Custody Banks'),
    ('BA', 'Boeing', 'Industrials', 0.0018, 'BA', 'Aerospace & Defense'),
    ('BKNG', 'Booking Holdings', 'Consumer Discretionary', 0.0021, 'BKNG', 'Hotels, Resorts & Cruise Lines'),
    ('BSX', 'Boston Scientific', 'Health Care', 0.0017, 'BSX', 'Health Care Equipment'),
    ('BMY', 'Bristol Myers Squibb', 'Health Care', 0.0017, 'BMY', 'Pharmaceuticals'),
    ('AVGO', 'Broadcom', 'Information Technology', 0.0023, 'AVGO', 'Semiconductors'),
    ('BR', 'Broadridge Financial Solutions', 'Industrials', 0.0018, 'BR', 'Data Processing & Outsourced Services'),
    ('BRO', 'Brown & Brown', 'Financials', 0.0017, 'BRO', 'Insurance Brokers'),
    ('BF-B', 'Brown–Forman', 'Consumer Staples', 0.0012, 'BF.B', 'Distillers & Vintners'),
    ('BLDR', 'Builders FirstSource', 'Industrials', 0.0018, 'BLDR', 'Building Products'),
    ('BG', 'Bunge Global', 'Consumer Staples', 0.0012, 'BG', 'Agricultural Products & Services'),
    ('BXP', 'BXP, Inc.', 'Real Estate', 0.0016, 'BXP', 'Office REITs'),
    ('CHRW', 'C.H. Robinson', 'Industrials', 0.0018, 'CHRW', 'Air Freight & Logistics'),
    ('CDNS', 'Cadence Design Systems', 'Information Technology', 0.0023, 'CDNS', 'Application Software'),
    ('CPT', 'Camden Property Trust', 'Real Estate', 0.0016, 'CPT', 'Multi-Family Residential REITs'),
    ('COF', 'Capital One', 'Financials', 0.0017, 'COF', 'Consumer Finance'),
    ('CAH', 'Cardinal Health', 'Health Care', 0.0017, 'CAH', 'Health Care Distributors'),
    ('CCL', 'Carnival Corporation', 'Consumer Discretionary', 0.0021, 'CCL', 'Hotels, Resorts & Cruise Lines'),
    ('CARR', 'Carrier Global', 'Industrials', 0.0018, 'CARR', 'Building Products'),
    ('CVNA', 'Carvana', 'Consumer Discretionary', 0.0021, 'CVNA', 'Automotive Retail'),
    ('CASY', "Casey's", 'Consumer Staples', 0.0012, 'CASY', 'Food Retail'),
    ('CAT', 'Caterpillar Inc.', 'Industrials', 0.0018, 'CAT', 'Construction Machinery & Heavy Transportation Equipment'),
    ('CBOE', 'Cboe Global Markets', 'Financials', 0.0017, 'CBOE', 'Financial Exchanges & Data'),
    ('CBRE', 'CBRE Group', 'Real Estate', 0.0016, 'CBRE', 'Real Estate Services'),
    ('CDW', 'CDW Corporation', 'Information Technology', 0.0023, 'CDW', 'Technology Distributors'),
    ('COR', 'Cencora', 'Health Care', 0.0017, 'COR', 'Health Care Distributors'),
    ('CNC', 'Centene Corporation', 'Health Care', 0.0017, 'CNC', 'Managed Health Care'),
    ('CNP', 'CenterPoint Energy', 'Utilities', 0.0012, 'CNP', 'Multi-Utilities'),
    ('CF', 'CF Industries', 'Materials', 0.002, 'CF', 'Fertilizers & Agricultural Chemicals'),
    ('CRL', 'Charles River Laboratories', 'Health Care', 0.0017, 'CRL', 'Life Sciences Tools & Services'),
    ('SCHW', 'Charles Schwab Corporation', 'Financials', 0.0017, 'SCHW', 'Investment Banking & Brokerage'),
    ('CHTR', 'Charter Communications', 'Communication Services', 0.0022, 'CHTR', 'Cable & Satellite'),
    ('CVX', 'Chevron Corporation', 'Energy', 0.0021, 'CVX', 'Integrated Oil & Gas'),
    ('CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary', 0.0021, 'CMG', 'Restaurants'),
    ('CB', 'Chubb Limited', 'Financials', 0.0017, 'CB', 'Property & Casualty Insurance'),
    ('CHD', 'Church & Dwight', 'Consumer Staples', 0.0012, 'CHD', 'Household Products'),
    ('CIEN', 'Ciena', 'Information Technology', 0.0023, 'CIEN', 'Communications Equipment'),
    ('CI', 'Cigna', 'Health Care', 0.0017, 'CI', 'Health Care Services'),
    ('CINF', 'Cincinnati Financial', 'Financials', 0.0017, 'CINF', 'Property & Casualty Insurance'),
    ('CTAS', 'Cintas', 'Industrials', 0.0018, 'CTAS', 'Diversified Support Services'),
    ('CSCO', 'Cisco', 'Information Technology', 0.0023, 'CSCO', 'Communications Equipment'),
    ('C', 'Citigroup', 'Financials', 0.0017, 'C', 'Diversified Banks'),
    ('CFG', 'Citizens Financial Group', 'Financials', 0.0017, 'CFG', 'Regional Banks'),
    ('CLX', 'Clorox', 'Consumer Staples', 0.0012, 'CLX', 'Household Products'),
    ('CME', 'CME Group', 'Financials', 0.0017, 'CME', 'Financial Exchanges & Data'),
    ('CMS', 'CMS Energy', 'Utilities', 0.0012, 'CMS', 'Multi-Utilities'),
    ('KO', 'Coca-Cola Company (The)', 'Consumer Staples', 0.0012, 'KO', 'Soft Drinks & Non-alcoholic Beverages'),
    ('CTSH', 'Cognizant', 'Information Technology', 0.0023, 'CTSH', 'IT Consulting & Other Services'),
    ('COHR', 'Coherent Corp.', 'Information Technology', 0.0023, 'COHR', 'Electronic Components'),
    ('COIN', 'Coinbase', 'Financials', 0.0017, 'COIN', 'Financial Exchanges & Data'),
    ('CL', 'Colgate-Palmolive', 'Consumer Staples', 0.0012, 'CL', 'Household Products'),
    ('CMCSA', 'Comcast', 'Communication Services', 0.0022, 'CMCSA', 'Cable & Satellite'),
    ('FIX', 'Comfort Systems USA', 'Industrials', 0.0018, 'FIX', 'Construction & Engineering'),
    ('COP', 'ConocoPhillips', 'Energy', 0.0021, 'COP', 'Oil & Gas Exploration & Production'),
    ('ED', 'Consolidated Edison', 'Utilities', 0.0012, 'ED', 'Multi-Utilities'),
    ('STZ', 'Constellation Brands', 'Consumer Staples', 0.0012, 'STZ', 'Distillers & Vintners'),
    ('CEG', 'Constellation Energy', 'Utilities', 0.0012, 'CEG', 'Electric Utilities'),
    ('COO', 'Cooper Companies (The)', 'Health Care', 0.0017, 'COO', 'Health Care Supplies'),
    ('CPRT', 'Copart', 'Industrials', 0.0018, 'CPRT', 'Diversified Support Services'),
    ('GLW', 'Corning Inc.', 'Information Technology', 0.0023, 'GLW', 'Electronic Components'),
    ('CPAY', 'Corpay', 'Financials', 0.0017, 'CPAY', 'Transaction & Payment Processing Services'),
    ('CTVA', 'Corteva', 'Materials', 0.002, 'CTVA', 'Fertilizers & Agricultural Chemicals'),
    ('CSGP', 'CoStar Group', 'Real Estate', 0.0016, 'CSGP', 'Real Estate Services'),
    ('COST', 'Costco', 'Consumer Staples', 0.0012, 'COST', 'Consumer Staples Merchandise Retail'),
    ('CRH', 'CRH plc', 'Materials', 0.002, 'CRH', 'Construction Materials'),
    ('CRWD', 'CrowdStrike', 'Information Technology', 0.0023, 'CRWD', 'Systems Software'),
    ('CCI', 'Crown Castle', 'Real Estate', 0.0016, 'CCI', 'Telecom Tower REITs'),
    ('CSX', 'CSX Corporation', 'Industrials', 0.0018, 'CSX', 'Rail Transportation'),
    ('CMI', 'Cummins', 'Industrials', 0.0018, 'CMI', 'Construction Machinery & Heavy Transportation Equipment'),
    ('CVS', 'CVS Health', 'Health Care', 0.0017, 'CVS', 'Health Care Services'),
    ('DHR', 'Danaher Corporation', 'Health Care', 0.0017, 'DHR', 'Life Sciences Tools & Services'),
    ('DRI', 'Darden Restaurants', 'Consumer Discretionary', 0.0021, 'DRI', 'Restaurants'),
    ('DDOG', 'Datadog', 'Information Technology', 0.0023, 'DDOG', 'Application Software'),
    ('DVA', 'DaVita', 'Health Care', 0.0017, 'DVA', 'Health Care Services'),
    ('DECK', 'Deckers Brands', 'Consumer Discretionary', 0.0021, 'DECK', 'Footwear'),
    ('DE', 'Deere & Company', 'Industrials', 0.0018, 'DE', 'Agricultural & Farm Machinery'),
    ('DELL', 'Dell Technologies', 'Information Technology', 0.0023, 'DELL', 'Technology Hardware, Storage & Peripherals'),
    ('DAL', 'Delta Air Lines', 'Industrials', 0.0018, 'DAL', 'Passenger Airlines'),
    ('DVN', 'Devon Energy', 'Energy', 0.0021, 'DVN', 'Oil & Gas Exploration & Production'),
    ('DXCM', 'Dexcom', 'Health Care', 0.0017, 'DXCM', 'Health Care Equipment'),
    ('FANG', 'Diamondback Energy', 'Energy', 0.0021, 'FANG', 'Oil & Gas Exploration & Production'),
    ('DLR', 'Digital Realty', 'Real Estate', 0.0016, 'DLR', 'Data Center REITs'),
    ('DG', 'Dollar General', 'Consumer Staples', 0.0012, 'DG', 'Consumer Staples Merchandise Retail'),
    ('DLTR', 'Dollar Tree', 'Consumer Staples', 0.0012, 'DLTR', 'Consumer Staples Merchandise Retail'),
    ('D', 'Dominion Energy', 'Utilities', 0.0012, 'D', 'Multi-Utilities'),
    ('DPZ', "Domino's", 'Consumer Discretionary', 0.0021, 'DPZ', 'Restaurants'),
    ('DASH', 'DoorDash', 'Consumer Discretionary', 0.0021, 'DASH', 'Specialized Consumer Services'),
    ('DOV', 'Dover Corporation', 'Industrials', 0.0018, 'DOV', 'Industrial Machinery & Supplies & Components'),
    ('DOW', 'Dow Inc.', 'Materials', 0.002, 'DOW', 'Commodity Chemicals'),
    ('DHI', 'D. R. Horton', 'Consumer Discretionary', 0.0021, 'DHI', 'Homebuilding'),
    ('DTE', 'DTE Energy', 'Utilities', 0.0012, 'DTE', 'Multi-Utilities'),
    ('DUK', 'Duke Energy', 'Utilities', 0.0012, 'DUK', 'Electric Utilities'),
    ('DD', 'DuPont', 'Industrials', 0.0018, 'DD', 'Industrial Conglomerates'),
    ('ETN', 'Eaton Corporation', 'Industrials', 0.0018, 'ETN', 'Electrical Components & Equipment'),
    ('EBAY', 'eBay Inc.', 'Consumer Discretionary', 0.0021, 'EBAY', 'Broadline Retail'),
    ('ECHO', 'EchoStar', 'Communication Services', 0.0022, 'ECHO', 'Wireless Telecommunication Services'),
    ('ECL', 'Ecolab', 'Materials', 0.002, 'ECL', 'Specialty Chemicals'),
    ('EIX', 'Edison International', 'Utilities', 0.0012, 'EIX', 'Electric Utilities'),
    ('EW', 'Edwards Lifesciences', 'Health Care', 0.0017, 'EW', 'Health Care Equipment'),
    ('ELV', 'Elevance Health', 'Health Care', 0.0017, 'ELV', 'Managed Health Care'),
    ('EME', 'Emcor', 'Industrials', 0.0018, 'EME', 'Construction & Engineering'),
    ('EMR', 'Emerson Electric', 'Industrials', 0.0018, 'EMR', 'Electrical Components & Equipment'),
    ('ETR', 'Entergy', 'Utilities', 0.0012, 'ETR', 'Electric Utilities'),
    ('EOG', 'EOG Resources', 'Energy', 0.0021, 'EOG', 'Oil & Gas Exploration & Production'),
    ('EQT', 'EQT Corporation', 'Energy', 0.0021, 'EQT', 'Oil & Gas Exploration & Production'),
    ('EFX', 'Equifax', 'Industrials', 0.0018, 'EFX', 'Research & Consulting Services'),
    ('EQIX', 'Equinix', 'Real Estate', 0.0016, 'EQIX', 'Data Center REITs'),
    ('ERIE', 'Erie Indemnity', 'Financials', 0.0017, 'ERIE', 'Insurance Brokers'),
    ('ESS', 'Essex Property Trust', 'Real Estate', 0.0016, 'ESS', 'Multi-Family Residential REITs'),
    ('EL', 'Estée Lauder Companies (The)', 'Consumer Staples', 0.0012, 'EL', 'Personal Care Products'),
    ('EG', 'Everest Group', 'Financials', 0.0017, 'EG', 'Reinsurance'),
    ('EVRG', 'Evergy', 'Utilities', 0.0012, 'EVRG', 'Electric Utilities'),
    ('ES', 'Eversource Energy', 'Utilities', 0.0012, 'ES', 'Electric Utilities'),
    ('EXC', 'Exelon', 'Utilities', 0.0012, 'EXC', 'Electric Utilities'),
    ('EXE', 'Expand Energy', 'Energy', 0.0021, 'EXE', 'Oil & Gas Exploration & Production'),
    ('EXPE', 'Expedia Group', 'Consumer Discretionary', 0.0021, 'EXPE', 'Hotels, Resorts & Cruise Lines'),
    ('EXPD', 'Expeditors International', 'Industrials', 0.0018, 'EXPD', 'Air Freight & Logistics'),
    ('EXR', 'Extra Space Storage', 'Real Estate', 0.0016, 'EXR', 'Self-Storage REITs'),
    ('XOM', 'ExxonMobil', 'Energy', 0.0021, 'XOM', 'Integrated Oil & Gas'),
    ('FFIV', 'F5, Inc.', 'Information Technology', 0.0023, 'FFIV', 'Communications Equipment'),
    ('FDS', 'FactSet', 'Financials', 0.0017, 'FDS', 'Financial Exchanges & Data'),
    ('FICO', 'Fair Isaac', 'Information Technology', 0.0023, 'FICO', 'Application Software'),
    ('FAST', 'Fastenal', 'Industrials', 0.0018, 'FAST', 'Trading Companies & Distributors'),
    ('FRT', 'Federal Realty Investment Trust', 'Real Estate', 0.0016, 'FRT', 'Retail REITs'),
    ('FDX', 'FedEx', 'Industrials', 0.0018, 'FDX', 'Air Freight & Logistics'),
    ('FDXF', 'FedEx Freight', 'Industrials', 0.0018, 'FDXF', 'Cargo Ground Transportation'),
    ('FERG', 'Ferguson Enterprises', 'Industrials', 0.0018, 'FERG', 'Building Products'),
    ('FIS', 'Fidelity National Information Services', 'Financials', 0.0017, 'FIS', 'Transaction & Payment Processing Services'),
    ('FITB', 'Fifth Third Bancorp', 'Financials', 0.0017, 'FITB', 'Regional Banks'),
    ('FSLR', 'First Solar', 'Information Technology', 0.0023, 'FSLR', 'Semiconductors'),
    ('FE', 'FirstEnergy', 'Utilities', 0.0012, 'FE', 'Electric Utilities'),
    ('FISV', 'Fiserv', 'Financials', 0.0017, 'FISV', 'Transaction & Payment Processing Services'),
    ('FLEX', 'Flex Ltd.', 'Information Technology', 0.0023, 'FLEX', 'Electronic Manufacturing Services'),
    ('F', 'Ford Motor Company', 'Consumer Discretionary', 0.0021, 'F', 'Automobile Manufacturers'),
    ('FTNT', 'Fortinet', 'Information Technology', 0.0023, 'FTNT', 'Systems Software'),
    ('FTV', 'Fortive', 'Industrials', 0.0018, 'FTV', 'Industrial Machinery & Supplies & Components'),
    ('FOXA', 'Fox Corporation (Class A)', 'Communication Services', 0.0022, 'FOXA', 'Broadcasting'),
    ('FOX', 'Fox Corporation (Class B)', 'Communication Services', 0.0022, 'FOX', 'Broadcasting'),
    ('BEN', 'Franklin Resources', 'Financials', 0.0017, 'BEN', 'Asset Management & Custody Banks'),
    ('FCX', 'Freeport-McMoRan', 'Materials', 0.002, 'FCX', 'Copper'),
    ('GRMN', 'Garmin', 'Consumer Discretionary', 0.0021, 'GRMN', 'Consumer Electronics'),
    ('IT', 'Gartner', 'Information Technology', 0.0023, 'IT', 'IT Consulting & Other Services'),
    ('GE', 'GE Aerospace', 'Industrials', 0.0018, 'GE', 'Aerospace & Defense'),
    ('GEHC', 'GE HealthCare', 'Health Care', 0.0017, 'GEHC', 'Health Care Equipment'),
    ('GEV', 'GE Vernova', 'Industrials', 0.0018, 'GEV', 'Heavy Electrical Equipment'),
    ('GEN', 'Gen Digital', 'Information Technology', 0.0023, 'GEN', 'Systems Software'),
    ('GNRC', 'Generac', 'Industrials', 0.0018, 'GNRC', 'Heavy Electrical Equipment'),
    ('GD', 'General Dynamics', 'Industrials', 0.0018, 'GD', 'Aerospace & Defense'),
    ('GIS', 'General Mills', 'Consumer Staples', 0.0012, 'GIS', 'Packaged Foods & Meats'),
    ('GM', 'General Motors', 'Consumer Discretionary', 0.0021, 'GM', 'Automobile Manufacturers'),
    ('GPC', 'Genuine Parts Company', 'Consumer Discretionary', 0.0021, 'GPC', 'Distributors'),
    ('GILD', 'Gilead Sciences', 'Health Care', 0.0017, 'GILD', 'Biotechnology'),
    ('GPN', 'Global Payments', 'Financials', 0.0017, 'GPN', 'Transaction & Payment Processing Services'),
    ('GL', 'Globe Life', 'Financials', 0.0017, 'GL', 'Life & Health Insurance'),
    ('GDDY', 'GoDaddy', 'Information Technology', 0.0023, 'GDDY', 'Internet Services & Infrastructure'),
    ('GS', 'Goldman Sachs', 'Financials', 0.0017, 'GS', 'Investment Banking & Brokerage'),
    ('HAL', 'Halliburton', 'Energy', 0.0021, 'HAL', 'Oil & Gas Equipment & Services'),
    ('HIG', 'Hartford (The)', 'Financials', 0.0017, 'HIG', 'Property & Casualty Insurance'),
    ('HAS', 'Hasbro', 'Consumer Discretionary', 0.0021, 'HAS', 'Leisure Products'),
    ('HCA', 'HCA Healthcare', 'Health Care', 0.0017, 'HCA', 'Health Care Facilities'),
    ('DOC', 'Healthpeak Properties', 'Real Estate', 0.0016, 'DOC', 'Health Care REITs'),
    ('HSIC', 'Henry Schein', 'Health Care', 0.0017, 'HSIC', 'Health Care Distributors'),
    ('HSY', 'Hershey Company (The)', 'Consumer Staples', 0.0012, 'HSY', 'Packaged Foods & Meats'),
    ('HPE', 'Hewlett Packard Enterprise', 'Information Technology', 0.0023, 'HPE', 'Technology Hardware, Storage & Peripherals'),
    ('HLT', 'Hilton Worldwide', 'Consumer Discretionary', 0.0021, 'HLT', 'Hotels, Resorts & Cruise Lines'),
    ('HD', 'Home Depot (The)', 'Consumer Discretionary', 0.0021, 'HD', 'Home Improvement Retail'),
    ('HONA', 'Honeywell Aerospace', 'Industrials', 0.0018, 'HONA', 'Aerospace & Defense'),
    ('HON', 'Honeywell Technologies', 'Industrials', 0.0018, 'HON', 'Industrial Conglomerates'),
    ('HRL', 'Hormel Foods', 'Consumer Staples', 0.0012, 'HRL', 'Packaged Foods & Meats'),
    ('HST', 'Host Hotels & Resorts', 'Real Estate', 0.0016, 'HST', 'Hotel & Resort REITs'),
    ('HWM', 'Howmet Aerospace', 'Industrials', 0.0018, 'HWM', 'Aerospace & Defense'),
    ('HPQ', 'HP Inc.', 'Information Technology', 0.0023, 'HPQ', 'Technology Hardware, Storage & Peripherals'),
    ('HUBB', 'Hubbell Incorporated', 'Industrials', 0.0018, 'HUBB', 'Industrial Machinery & Supplies & Components'),
    ('HUM', 'Humana', 'Health Care', 0.0017, 'HUM', 'Managed Health Care'),
    ('HBAN', 'Huntington Bancshares', 'Financials', 0.0017, 'HBAN', 'Regional Banks'),
    ('HII', 'Huntington Ingalls Industries', 'Industrials', 0.0018, 'HII', 'Aerospace & Defense'),
    ('IBM', 'IBM', 'Information Technology', 0.0023, 'IBM', 'IT Consulting & Other Services'),
    ('IEX', 'IDEX Corporation', 'Industrials', 0.0018, 'IEX', 'Industrial Machinery & Supplies & Components'),
    ('IDXX', 'Idexx Laboratories', 'Health Care', 0.0017, 'IDXX', 'Health Care Equipment'),
    ('ITW', 'Illinois Tool Works', 'Industrials', 0.0018, 'ITW', 'Industrial Machinery & Supplies & Components'),
    ('INCY', 'Incyte', 'Health Care', 0.0017, 'INCY', 'Biotechnology'),
    ('IR', 'Ingersoll Rand', 'Industrials', 0.0018, 'IR', 'Industrial Machinery & Supplies & Components'),
    ('PODD', 'Insulet Corporation', 'Health Care', 0.0017, 'PODD', 'Health Care Equipment'),
    ('INTC', 'Intel', 'Information Technology', 0.0023, 'INTC', 'Semiconductors'),
    ('IBKR', 'Interactive Brokers', 'Financials', 0.0017, 'IBKR', 'Investment Banking & Brokerage'),
    ('ICE', 'Intercontinental Exchange', 'Financials', 0.0017, 'ICE', 'Financial Exchanges & Data'),
    ('IFF', 'International Flavors & Fragrances', 'Materials', 0.002, 'IFF', 'Specialty Chemicals'),
    ('IP', 'International Paper', 'Materials', 0.002, 'IP', 'Paper & Plastic Packaging Products & Materials'),
    ('INTU', 'Intuit', 'Information Technology', 0.0023, 'INTU', 'Application Software'),
    ('ISRG', 'Intuitive Surgical', 'Health Care', 0.0017, 'ISRG', 'Health Care Equipment'),
    ('IVZ', 'Invesco', 'Financials', 0.0017, 'IVZ', 'Asset Management & Custody Banks'),
    ('INVH', 'Invitation Homes', 'Real Estate', 0.0016, 'INVH', 'Single-Family Residential REITs'),
    ('IQV', 'IQVIA', 'Health Care', 0.0017, 'IQV', 'Life Sciences Tools & Services'),
    ('IRM', 'Iron Mountain', 'Real Estate', 0.0016, 'IRM', 'Other Specialized REITs'),
    ('JBHT', 'J.B. Hunt', 'Industrials', 0.0018, 'JBHT', 'Cargo Ground Transportation'),
    ('JBL', 'Jabil', 'Information Technology', 0.0023, 'JBL', 'Electronic Manufacturing Services'),
    ('JKHY', 'Jack Henry & Associates', 'Financials', 0.0017, 'JKHY', 'Transaction & Payment Processing Services'),
    ('J', 'Jacobs Solutions', 'Industrials', 0.0018, 'J', 'Construction & Engineering'),
    ('JNJ', 'Johnson & Johnson', 'Health Care', 0.0017, 'JNJ', 'Pharmaceuticals'),
    ('JCI', 'Johnson Controls', 'Industrials', 0.0018, 'JCI', 'Building Products'),
    ('JPM', 'JPMorgan Chase', 'Financials', 0.0017, 'JPM', 'Diversified Banks'),
    ('KVUE', 'Kenvue', 'Consumer Staples', 0.0012, 'KVUE', 'Personal Care Products'),
    ('KDP', 'Keurig Dr Pepper', 'Consumer Staples', 0.0012, 'KDP', 'Soft Drinks & Non-alcoholic Beverages'),
    ('KEY', 'KeyCorp', 'Financials', 0.0017, 'KEY', 'Regional Banks'),
    ('KEYS', 'Keysight Technologies', 'Information Technology', 0.0023, 'KEYS', 'Electronic Equipment & Instruments'),
    ('KMB', 'Kimberly-Clark', 'Consumer Staples', 0.0012, 'KMB', 'Household Products'),
    ('KIM', 'Kimco Realty', 'Real Estate', 0.0016, 'KIM', 'Retail REITs'),
    ('KMI', 'Kinder Morgan', 'Energy', 0.0021, 'KMI', 'Oil & Gas Storage & Transportation'),
    ('KKR', 'KKR & Co.', 'Financials', 0.0017, 'KKR', 'Asset Management & Custody Banks'),
    ('KLAC', 'KLA Corporation', 'Information Technology', 0.0023, 'KLAC', 'Semiconductor Materials & Equipment'),
    ('KHC', 'Kraft Heinz', 'Consumer Staples', 0.0012, 'KHC', 'Packaged Foods & Meats'),
    ('KR', 'Kroger', 'Consumer Staples', 0.0012, 'KR', 'Food Retail'),
    ('LHX', 'L3Harris', 'Industrials', 0.0018, 'LHX', 'Aerospace & Defense'),
    ('LH', 'Labcorp', 'Health Care', 0.0017, 'LH', 'Health Care Services'),
    ('LRCX', 'Lam Research', 'Information Technology', 0.0023, 'LRCX', 'Semiconductor Materials & Equipment'),
    ('LVS', 'Las Vegas Sands', 'Consumer Discretionary', 0.0021, 'LVS', 'Casinos & Gaming'),
    ('LDOS', 'Leidos', 'Industrials', 0.0018, 'LDOS', 'Diversified Support Services'),
    ('LEN', 'Lennar', 'Consumer Discretionary', 0.0021, 'LEN', 'Homebuilding'),
    ('LII', 'Lennox International', 'Industrials', 0.0018, 'LII', 'Building Products'),
    ('LLY', 'Lilly (Eli)', 'Health Care', 0.0017, 'LLY', 'Pharmaceuticals'),
    ('LIN', 'Linde plc', 'Materials', 0.002, 'LIN', 'Industrial Gases'),
    ('LYV', 'Live Nation Entertainment', 'Communication Services', 0.0022, 'LYV', 'Movies & Entertainment'),
    ('LMT', 'Lockheed Martin', 'Industrials', 0.0018, 'LMT', 'Aerospace & Defense'),
    ('L', 'Loews Corporation', 'Financials', 0.0017, 'L', 'Multi-line Insurance'),
    ('LOW', "Lowe's", 'Consumer Discretionary', 0.0021, 'LOW', 'Home Improvement Retail'),
    ('LULU', 'Lululemon Athletica', 'Consumer Discretionary', 0.0021, 'LULU', 'Apparel, Accessories & Luxury Goods'),
    ('LITE', 'Lumentum', 'Information Technology', 0.0023, 'LITE', 'Communications Equipment'),
    ('LYB', 'LyondellBasell', 'Materials', 0.002, 'LYB', 'Specialty Chemicals'),
    ('MTB', 'M&T Bank', 'Financials', 0.0017, 'MTB', 'Regional Banks'),
    ('MPC', 'Marathon Petroleum', 'Energy', 0.0021, 'MPC', 'Oil & Gas Refining & Marketing'),
    ('MAR', 'Marriott International', 'Consumer Discretionary', 0.0021, 'MAR', 'Hotels, Resorts & Cruise Lines'),
    ('MRSH', 'Marsh McLennan', 'Financials', 0.0017, 'MRSH', 'Insurance Brokers'),
    ('MLM', 'Martin Marietta Materials', 'Materials', 0.002, 'MLM', 'Construction Materials'),
    ('MRVL', 'Marvell Technology', 'Information Technology', 0.0023, 'MRVL', 'Semiconductors'),
    ('MAS', 'Masco', 'Industrials', 0.0018, 'MAS', 'Building Products'),
    ('MA', 'Mastercard', 'Financials', 0.0017, 'MA', 'Transaction & Payment Processing Services'),
    ('MKC', 'McCormick & Company', 'Consumer Staples', 0.0012, 'MKC', 'Packaged Foods & Meats'),
    ('MCD', "McDonald's", 'Consumer Discretionary', 0.0021, 'MCD', 'Restaurants'),
    ('MCK', 'McKesson Corporation', 'Health Care', 0.0017, 'MCK', 'Health Care Distributors'),
    ('MDT', 'Medtronic', 'Health Care', 0.0017, 'MDT', 'Health Care Equipment'),
    ('MRK', 'Merck & Co.', 'Health Care', 0.0017, 'MRK', 'Pharmaceuticals'),
    ('META', 'Meta Platforms', 'Communication Services', 0.0022, 'META', 'Interactive Media & Services'),
    ('MET', 'MetLife', 'Financials', 0.0017, 'MET', 'Life & Health Insurance'),
    ('MTD', 'Mettler Toledo', 'Health Care', 0.0017, 'MTD', 'Life Sciences Tools & Services'),
    ('MGM', 'MGM Resorts', 'Consumer Discretionary', 0.0021, 'MGM', 'Casinos & Gaming'),
    ('MCHP', 'Microchip Technology', 'Information Technology', 0.0023, 'MCHP', 'Semiconductors'),
    ('MU', 'Micron Technology', 'Information Technology', 0.0023, 'MU', 'Semiconductors'),
    ('MSFT', 'Microsoft', 'Information Technology', 0.0023, 'MSFT', 'Systems Software'),
    ('MAA', 'Mid-America Apartment Communities', 'Real Estate', 0.0016, 'MAA', 'Multi-Family Residential REITs'),
    ('MRNA', 'Moderna', 'Health Care', 0.0017, 'MRNA', 'Biotechnology'),
    ('TAP', 'Molson Coors Beverage Company', 'Consumer Staples', 0.0012, 'TAP', 'Brewers'),
    ('MDLZ', 'Mondelez International', 'Consumer Staples', 0.0012, 'MDLZ', 'Packaged Foods & Meats'),
    ('MPWR', 'Monolithic Power Systems', 'Information Technology', 0.0023, 'MPWR', 'Semiconductors'),
    ('MNST', 'Monster Beverage', 'Consumer Staples', 0.0012, 'MNST', 'Soft Drinks & Non-alcoholic Beverages'),
    ('MCO', "Moody's Corporation", 'Financials', 0.0017, 'MCO', 'Financial Exchanges & Data'),
    ('MS', 'Morgan Stanley', 'Financials', 0.0017, 'MS', 'Investment Banking & Brokerage'),
    ('MOS', 'Mosaic Company (The)', 'Materials', 0.002, 'MOS', 'Fertilizers & Agricultural Chemicals'),
    ('MSI', 'Motorola Solutions', 'Information Technology', 0.0023, 'MSI', 'Communications Equipment'),
    ('MSCI', 'MSCI', 'Financials', 0.0017, 'MSCI', 'Financial Exchanges & Data'),
    ('NDAQ', 'Nasdaq, Inc.', 'Financials', 0.0017, 'NDAQ', 'Financial Exchanges & Data'),
    ('NTAP', 'NetApp', 'Information Technology', 0.0023, 'NTAP', 'Technology Hardware, Storage & Peripherals'),
    ('NFLX', 'Netflix', 'Communication Services', 0.0022, 'NFLX', 'Movies & Entertainment'),
    ('NEM', 'Newmont', 'Materials', 0.002, 'NEM', 'Gold'),
    ('NWSA', 'News Corp (Class A)', 'Communication Services', 0.0022, 'NWSA', 'Publishing'),
    ('NWS', 'News Corp (Class B)', 'Communication Services', 0.0022, 'NWS', 'Publishing'),
    ('NEE', 'NextEra Energy', 'Utilities', 0.0012, 'NEE', 'Multi-Utilities'),
    ('NKE', 'Nike, Inc.', 'Consumer Discretionary', 0.0021, 'NKE', 'Apparel, Accessories & Luxury Goods'),
    ('NI', 'NiSource', 'Utilities', 0.0012, 'NI', 'Multi-Utilities'),
    ('NDSN', 'Nordson Corporation', 'Industrials', 0.0018, 'NDSN', 'Industrial Machinery & Supplies & Components'),
    ('NSC', 'Norfolk Southern', 'Industrials', 0.0018, 'NSC', 'Rail Transportation'),
    ('NTRS', 'Northern Trust', 'Financials', 0.0017, 'NTRS', 'Asset Management & Custody Banks'),
    ('NOC', 'Northrop Grumman', 'Industrials', 0.0018, 'NOC', 'Aerospace & Defense'),
    ('NCLH', 'Norwegian Cruise Line Holdings', 'Consumer Discretionary', 0.0021, 'NCLH', 'Hotels, Resorts & Cruise Lines'),
    ('NRG', 'NRG Energy', 'Utilities', 0.0012, 'NRG', 'Independent Power Producers & Energy Traders'),
    ('NUE', 'Nucor', 'Materials', 0.002, 'NUE', 'Steel'),
    ('NVDA', 'Nvidia', 'Information Technology', 0.0023, 'NVDA', 'Semiconductors'),
    ('NVR', 'NVR, Inc.', 'Consumer Discretionary', 0.0021, 'NVR', 'Homebuilding'),
    ('NXPI', 'NXP Semiconductors', 'Information Technology', 0.0023, 'NXPI', 'Semiconductors'),
    ('ORLY', "O'Reilly Automotive", 'Consumer Discretionary', 0.0021, 'ORLY', 'Automotive Retail'),
    ('OXY', 'Occidental Petroleum', 'Energy', 0.0021, 'OXY', 'Oil & Gas Exploration & Production'),
    ('ODFL', 'Old Dominion', 'Industrials', 0.0018, 'ODFL', 'Cargo Ground Transportation'),
    ('OMC', 'Omnicom Group', 'Communication Services', 0.0022, 'OMC', 'Advertising'),
    ('ON', 'ON Semiconductor', 'Information Technology', 0.0023, 'ON', 'Semiconductors'),
    ('OKE', 'Oneok', 'Energy', 0.0021, 'OKE', 'Oil & Gas Storage & Transportation'),
    ('ORCL', 'Oracle Corporation', 'Information Technology', 0.0023, 'ORCL', 'Application Software'),
    ('OTIS', 'Otis Worldwide', 'Industrials', 0.0018, 'OTIS', 'Industrial Machinery & Supplies & Components'),
    ('PCAR', 'Paccar', 'Industrials', 0.0018, 'PCAR', 'Construction Machinery & Heavy Transportation Equipment'),
    ('PKG', 'Packaging Corporation of America', 'Materials', 0.002, 'PKG', 'Paper & Plastic Packaging Products & Materials'),
    ('PLTR', 'Palantir Technologies', 'Information Technology', 0.0023, 'PLTR', 'Application Software'),
    ('PANW', 'Palo Alto Networks', 'Information Technology', 0.0023, 'PANW', 'Systems Software'),
    ('PSKY', 'Paramount Skydance Corporation', 'Communication Services', 0.0022, 'PSKY', 'Movies & Entertainment'),
    ('PH', 'Parker Hannifin', 'Industrials', 0.0018, 'PH', 'Industrial Machinery & Supplies & Components'),
    ('PAYX', 'Paychex', 'Industrials', 0.0018, 'PAYX', 'Human Resource & Employment Services'),
    ('PYPL', 'PayPal', 'Financials', 0.0017, 'PYPL', 'Transaction & Payment Processing Services'),
    ('PNR', 'Pentair', 'Industrials', 0.0018, 'PNR', 'Industrial Machinery & Supplies & Components'),
    ('PEP', 'PepsiCo', 'Consumer Staples', 0.0012, 'PEP', 'Soft Drinks & Non-alcoholic Beverages'),
    ('PFE', 'Pfizer', 'Health Care', 0.0017, 'PFE', 'Pharmaceuticals'),
    ('PCG', 'PG&E Corporation', 'Utilities', 0.0012, 'PCG', 'Multi-Utilities'),
    ('PM', 'Philip Morris International', 'Consumer Staples', 0.0012, 'PM', 'Tobacco'),
    ('PSX', 'Phillips 66', 'Energy', 0.0021, 'PSX', 'Oil & Gas Refining & Marketing'),
    ('PNW', 'Pinnacle West Capital', 'Utilities', 0.0012, 'PNW', 'Multi-Utilities'),
    ('PNC', 'PNC Financial Services', 'Financials', 0.0017, 'PNC', 'Diversified Banks'),
    ('PPG', 'PPG Industries', 'Materials', 0.002, 'PPG', 'Specialty Chemicals'),
    ('PPL', 'PPL Corporation', 'Utilities', 0.0012, 'PPL', 'Electric Utilities'),
    ('PFG', 'Principal Financial Group', 'Financials', 0.0017, 'PFG', 'Life & Health Insurance'),
    ('PG', 'Procter & Gamble', 'Consumer Staples', 0.0012, 'PG', 'Personal Care Products'),
    ('PGR', 'Progressive Corporation', 'Financials', 0.0017, 'PGR', 'Property & Casualty Insurance'),
    ('PLD', 'Prologis', 'Real Estate', 0.0016, 'PLD', 'Industrial REITs'),
    ('PRU', 'Prudential Financial', 'Financials', 0.0017, 'PRU', 'Life & Health Insurance'),
    ('PEG', 'Public Service Enterprise Group', 'Utilities', 0.0012, 'PEG', 'Electric Utilities'),
    ('PTC', 'PTC Inc.', 'Information Technology', 0.0023, 'PTC', 'Application Software'),
    ('PSA', 'Public Storage', 'Real Estate', 0.0016, 'PSA', 'Self-Storage REITs'),
    ('PHM', 'PulteGroup', 'Consumer Discretionary', 0.0021, 'PHM', 'Homebuilding'),
    ('PWR', 'Quanta Services', 'Industrials', 0.0018, 'PWR', 'Construction & Engineering'),
    ('QCOM', 'Qualcomm', 'Information Technology', 0.0023, 'QCOM', 'Semiconductors'),
    ('DGX', 'Quest Diagnostics', 'Health Care', 0.0017, 'DGX', 'Health Care Services'),
    ('Q', 'Qnity Electronics', 'Information Technology', 0.0023, 'Q', 'Semiconductor Materials & Equipment'),
    ('RL', 'Ralph Lauren Corporation', 'Consumer Discretionary', 0.0021, 'RL', 'Apparel, Accessories & Luxury Goods'),
    ('RJF', 'Raymond James Financial', 'Financials', 0.0017, 'RJF', 'Investment Banking & Brokerage'),
    ('RDDT', 'Reddit', 'Communication Services', 0.0022, 'RDDT', 'Interactive Media & Services'),
    ('RTX', 'RTX Corporation', 'Industrials', 0.0018, 'RTX', 'Aerospace & Defense'),
    ('O', 'Realty Income', 'Real Estate', 0.0016, 'O', 'Retail REITs'),
    ('REG', 'Regency Centers', 'Real Estate', 0.0016, 'REG', 'Retail REITs'),
    ('REGN', 'Regeneron Pharmaceuticals', 'Health Care', 0.0017, 'REGN', 'Biotechnology'),
    ('RF', 'Regions Financial Corporation', 'Financials', 0.0017, 'RF', 'Regional Banks'),
    ('RSG', 'Republic Services', 'Industrials', 0.0018, 'RSG', 'Environmental & Facilities Services'),
    ('RMD', 'ResMed|', 'Health Care', 0.0017, 'RMD', 'Health Care Equipment'),
    ('RVTY', 'Revvity', 'Health Care', 0.0017, 'RVTY', 'Health Care Equipment'),
    ('HOOD', 'Robinhood Markets', 'Financials', 0.0017, 'HOOD', 'Investment Banking & Brokerage'),
    ('ROK', 'Rockwell Automation', 'Industrials', 0.0018, 'ROK', 'Electrical Components & Equipment'),
    ('ROL', 'Rollins, Inc.', 'Industrials', 0.0018, 'ROL', 'Environmental & Facilities Services'),
    ('ROP', 'Roper Technologies', 'Information Technology', 0.0023, 'ROP', 'Electronic Equipment & Instruments'),
    ('ROST', 'Ross Stores', 'Consumer Discretionary', 0.0021, 'ROST', 'Apparel Retail'),
    ('RCL', 'Royal Caribbean Group', 'Consumer Discretionary', 0.0021, 'RCL', 'Hotels, Resorts & Cruise Lines'),
    ('SPGI', 'S&P Global', 'Financials', 0.0017, 'SPGI', 'Financial Exchanges & Data'),
    ('CRM', 'Salesforce', 'Information Technology', 0.0023, 'CRM', 'Application Software'),
    ('SNDK', 'Sandisk', 'Information Technology', 0.0023, 'SNDK', 'Technology Hardware, Storage & Peripherals'),
    ('SBAC', 'SBA Communications', 'Real Estate', 0.0016, 'SBAC', 'Telecom Tower REITs'),
    ('SLB', 'Schlumberger', 'Energy', 0.0021, 'SLB', 'Oil & Gas Equipment & Services'),
    ('STX', 'Seagate Technology', 'Information Technology', 0.0023, 'STX', 'Technology Hardware, Storage & Peripherals'),
    ('SRE', 'Sempra', 'Utilities', 0.0012, 'SRE', 'Multi-Utilities'),
    ('NOW', 'ServiceNow', 'Information Technology', 0.0023, 'NOW', 'Systems Software'),
    ('SHW', 'Sherwin-Williams', 'Materials', 0.002, 'SHW', 'Specialty Chemicals'),
    ('SPG', 'Simon Property Group', 'Real Estate', 0.0016, 'SPG', 'Retail REITs'),
    ('SWKS', 'Skyworks Solutions', 'Information Technology', 0.0023, 'SWKS', 'Semiconductors'),
    ('SJM', 'J.M. Smucker Company (The)', 'Consumer Staples', 0.0012, 'SJM', 'Packaged Foods & Meats'),
    ('SW', 'Smurfit Westrock', 'Materials', 0.002, 'SW', 'Paper & Plastic Packaging Products & Materials'),
    ('SNA', 'Snap-on', 'Industrials', 0.0018, 'SNA', 'Industrial Machinery & Supplies & Components'),
    ('SOLV', 'Solventum', 'Health Care', 0.0017, 'SOLV', 'Health Care Technology'),
    ('SO', 'Southern Company', 'Utilities', 0.0012, 'SO', 'Electric Utilities'),
    ('LUV', 'Southwest Airlines', 'Industrials', 0.0018, 'LUV', 'Passenger Airlines'),
    ('SWK', 'Stanley Black & Decker', 'Industrials', 0.0018, 'SWK', 'Industrial Machinery & Supplies & Components'),
    ('SBUX', 'Starbucks', 'Consumer Discretionary', 0.0021, 'SBUX', 'Restaurants'),
    ('STT', 'State Street Corporation', 'Financials', 0.0017, 'STT', 'Asset Management & Custody Banks'),
    ('STLD', 'Steel Dynamics', 'Materials', 0.002, 'STLD', 'Steel'),
    ('STE', 'Steris', 'Health Care', 0.0017, 'STE', 'Health Care Equipment'),
    ('SYK', 'Stryker Corporation', 'Health Care', 0.0017, 'SYK', 'Health Care Equipment'),
    ('SMCI', 'Supermicro', 'Information Technology', 0.0023, 'SMCI', 'Technology Hardware, Storage & Peripherals'),
    ('SYF', 'Synchrony Financial', 'Financials', 0.0017, 'SYF', 'Consumer Finance'),
    ('SNPS', 'Synopsys', 'Information Technology', 0.0023, 'SNPS', 'Application Software'),
    ('SYY', 'Sysco', 'Consumer Staples', 0.0012, 'SYY', 'Food Distributors'),
    ('TMUS', 'T-Mobile US', 'Communication Services', 0.0022, 'TMUS', 'Wireless Telecommunication Services'),
    ('TROW', 'T. Rowe Price', 'Financials', 0.0017, 'TROW', 'Asset Management & Custody Banks'),
    ('TTWO', 'Take-Two Interactive', 'Communication Services', 0.0022, 'TTWO', 'Interactive Home Entertainment'),
    ('TPR', 'Tapestry, Inc.', 'Consumer Discretionary', 0.0021, 'TPR', 'Apparel, Accessories & Luxury Goods'),
    ('TRGP', 'Targa Resources', 'Energy', 0.0021, 'TRGP', 'Oil & Gas Storage & Transportation'),
    ('TGT', 'Target Corporation', 'Consumer Staples', 0.0012, 'TGT', 'Consumer Staples Merchandise Retail'),
    ('TEL', 'TE Connectivity', 'Information Technology', 0.0023, 'TEL', 'Electronic Manufacturing Services'),
    ('TDY', 'Teledyne Technologies', 'Information Technology', 0.0023, 'TDY', 'Electronic Equipment & Instruments'),
    ('TER', 'Teradyne', 'Information Technology', 0.0023, 'TER', 'Semiconductor Materials & Equipment'),
    ('TSLA', 'Tesla, Inc.', 'Consumer Discretionary', 0.0021, 'TSLA', 'Automobile Manufacturers'),
    ('TXN', 'Texas Instruments', 'Information Technology', 0.0023, 'TXN', 'Semiconductors'),
    ('TPL', 'Texas Pacific Land Corporation', 'Energy', 0.0021, 'TPL', 'Oil & Gas Exploration & Production'),
    ('TXT', 'Textron', 'Industrials', 0.0018, 'TXT', 'Aerospace & Defense'),
    ('TMO', 'Thermo Fisher Scientific', 'Health Care', 0.0017, 'TMO', 'Life Sciences Tools & Services'),
    ('TJX', 'TJX Companies', 'Consumer Discretionary', 0.0021, 'TJX', 'Apparel Retail'),
    ('TKO', 'TKO Group Holdings', 'Communication Services', 0.0022, 'TKO', 'Movies & Entertainment'),
    ('TTD', 'Trade Desk (The)', 'Communication Services', 0.0022, 'TTD', 'Advertising'),
    ('TSCO', 'Tractor Supply', 'Consumer Discretionary', 0.0021, 'TSCO', 'Other Specialty Retail'),
    ('TT', 'Trane Technologies', 'Industrials', 0.0018, 'TT', 'Building Products'),
    ('TDG', 'TransDigm Group', 'Industrials', 0.0018, 'TDG', 'Aerospace & Defense'),
    ('TRV', 'Travelers Companies (The)', 'Financials', 0.0017, 'TRV', 'Property & Casualty Insurance'),
    ('TRMB', 'Trimble Inc.', 'Information Technology', 0.0023, 'TRMB', 'Application Software'),
    ('TFC', 'Truist Financial', 'Financials', 0.0017, 'TFC', 'Diversified Banks'),
    ('TYL', 'Tyler Technologies', 'Information Technology', 0.0023, 'TYL', 'Application Software'),
    ('TSN', 'Tyson Foods', 'Consumer Staples', 0.0012, 'TSN', 'Packaged Foods & Meats'),
    ('USB', 'U.S. Bancorp', 'Financials', 0.0017, 'USB', 'Diversified Banks'),
    ('UBER', 'Uber', 'Industrials', 0.0018, 'UBER', 'Passenger Ground Transportation'),
    ('UDR', 'UDR, Inc.', 'Real Estate', 0.0016, 'UDR', 'Multi-Family Residential REITs'),
    ('ULTA', 'Ulta Beauty', 'Consumer Discretionary', 0.0021, 'ULTA', 'Other Specialty Retail'),
    ('UNP', 'Union Pacific Corporation', 'Industrials', 0.0018, 'UNP', 'Rail Transportation'),
    ('UAL', 'United Airlines Holdings', 'Industrials', 0.0018, 'UAL', 'Passenger Airlines'),
    ('UPS', 'United Parcel Service', 'Industrials', 0.0018, 'UPS', 'Air Freight & Logistics'),
    ('URI', 'United Rentals', 'Industrials', 0.0018, 'URI', 'Trading Companies & Distributors'),
    ('UNH', 'UnitedHealth Group', 'Health Care', 0.0017, 'UNH', 'Managed Health Care'),
    ('UHS', 'Universal Health Services', 'Health Care', 0.0017, 'UHS', 'Health Care Facilities'),
    ('VLO', 'Valero Energy', 'Energy', 0.0021, 'VLO', 'Oil & Gas Refining & Marketing'),
    ('VEEV', 'Veeva Systems', 'Health Care', 0.0017, 'VEEV', 'Health Care Technology'),
    ('VTR', 'Ventas', 'Real Estate', 0.0016, 'VTR', 'Health Care REITs'),
    ('VLTO', 'Veralto', 'Industrials', 0.0018, 'VLTO', 'Environmental & Facilities Services'),
    ('VRSN', 'Verisign', 'Information Technology', 0.0023, 'VRSN', 'Internet Services & Infrastructure'),
    ('VRSK', 'Verisk Analytics', 'Industrials', 0.0018, 'VRSK', 'Research & Consulting Services'),
    ('VZ', 'Verizon', 'Communication Services', 0.0022, 'VZ', 'Integrated Telecommunication Services'),
    ('VRTX', 'Vertex Pharmaceuticals', 'Health Care', 0.0017, 'VRTX', 'Biotechnology'),
    ('VRT', 'Vertiv', 'Industrials', 0.0018, 'VRT', 'Electrical Components & Equipment'),
    ('VTRS', 'Viatris', 'Health Care', 0.0017, 'VTRS', 'Pharmaceuticals'),
    ('VICI', 'Vici Properties', 'Real Estate', 0.0016, 'VICI', 'Hotel & Resort REITs'),
    ('V', 'Visa Inc.', 'Financials', 0.0017, 'V', 'Transaction & Payment Processing Services'),
    ('VST', 'Vistra Corp.', 'Utilities', 0.0012, 'VST', 'Electric Utilities'),
    ('VMRK', 'Vivmark Residential', 'Real Estate', 0.0016, 'VMRK', 'Multi-Family Residential REITs'),
    ('VMC', 'Vulcan Materials Company', 'Materials', 0.002, 'VMC', 'Construction Materials'),
    ('WRB', 'W. R. Berkley Corporation', 'Financials', 0.0017, 'WRB', 'Property & Casualty Insurance'),
    ('GWW', 'W. W. Grainger', 'Industrials', 0.0018, 'GWW', 'Industrial Machinery & Supplies & Components'),
    ('WAB', 'Wabtec', 'Industrials', 0.0018, 'WAB', 'Construction Machinery & Heavy Transportation Equipment'),
    ('WMT', 'Walmart', 'Consumer Staples', 0.0012, 'WMT', 'Consumer Staples Merchandise Retail'),
    ('DIS', 'Walt Disney Company (The)', 'Communication Services', 0.0022, 'DIS', 'Movies & Entertainment'),
    ('WBD', 'Warner Bros. Discovery', 'Communication Services', 0.0022, 'WBD', 'Broadcasting'),
    ('WM', 'Waste Management', 'Industrials', 0.0018, 'WM', 'Environmental & Facilities Services'),
    ('WAT', 'Waters Corporation', 'Health Care', 0.0017, 'WAT', 'Life Sciences Tools & Services'),
    ('WEC', 'WEC Energy Group', 'Utilities', 0.0012, 'WEC', 'Electric Utilities'),
    ('WFC', 'Wells Fargo', 'Financials', 0.0017, 'WFC', 'Diversified Banks'),
    ('WELL', 'Welltower', 'Real Estate', 0.0016, 'WELL', 'Health Care REITs'),
    ('WST', 'West Pharmaceutical Services', 'Health Care', 0.0017, 'WST', 'Health Care Supplies'),
    ('WDC', 'Western Digital', 'Information Technology', 0.0023, 'WDC', 'Technology Hardware, Storage & Peripherals'),
    ('WY', 'Weyerhaeuser', 'Real Estate', 0.0016, 'WY', 'Timber REITs'),
    ('WSM', 'Williams-Sonoma, Inc.', 'Consumer Discretionary', 0.0021, 'WSM', 'Homefurnishing Retail'),
    ('WMB', 'Williams Companies', 'Energy', 0.0021, 'WMB', 'Oil & Gas Storage & Transportation'),
    ('WTW', 'Willis Towers Watson', 'Financials', 0.0017, 'WTW', 'Insurance Brokers'),
    ('WDAY', 'Workday, Inc.', 'Information Technology', 0.0023, 'WDAY', 'Application Software'),
    ('WYNN', 'Wynn Resorts', 'Consumer Discretionary', 0.0021, 'WYNN', 'Casinos & Gaming'),
    ('XEL', 'Xcel Energy', 'Utilities', 0.0012, 'XEL', 'Multi-Utilities'),
    ('XYL', 'Xylem Inc.', 'Industrials', 0.0018, 'XYL', 'Industrial Machinery & Supplies & Components'),
    ('YUM', 'Yum! Brands', 'Consumer Discretionary', 0.0021, 'YUM', 'Restaurants'),
    ('ZBRA', 'Zebra Technologies', 'Information Technology', 0.0023, 'ZBRA', 'Electronic Equipment & Instruments'),
    ('ZBH', 'Zimmer Biomet', 'Health Care', 0.0017, 'ZBH', 'Health Care Equipment'),
    ('ZTS', 'Zoetis', 'Health Care', 0.0017, 'ZTS', 'Pharmaceuticals'),
]
SP500_SYMBOLS=[r[0] for r in SP500_CONSTITUENTS]
